#!/usr/bin/env bash
# configure web 02 to web 01

sudo apt-get -y update
sudo apt-get -y install nginx
sudo sed -i "21s/^listen .*/listen 80" /etc/nginx/sites-enabled/default
sudo ufw allow 'Nginx HTTP'
sudo chmod 666 /var/www/html
sudo chmod 755 /var/www
echo "Hello World!" | sudo tee /var/www/html/index.nginx-debian.html
file=/etc/nginx/sites-enabled/default
redirect="\     rewrite ^/redirect_me https://www.youtube.com/watch?v=QH2-TGUlwu4/$1";
header="\    add_header X-Served-By $HOSTNAME;"
sudo sed -i "/server_name _;/a ${header}" $file
sudo service nginx restart
