#!/usr/bin/env bash
#fix container so that nginx is runnig as nginx user

chmod 777 /etc/nginx/nginx.conf
sudo sed -i "s/user www-data/user nginx" /etc/nginx/nginx.conf
sudo sed -i "s/80/8080/g" /etc/nginx/sites-available/default
pkill apache2
sudo -u nginx service nginx restart
